remote_theme: daattali/beautiful-jekyll

title: infra.ws

author: Copyright INFRAWS P.C. All Rights Reserved

navbar-links:
  Who We are: "/#who-we-are"
  What We Do: "/#what-we-do"
  Talk to us: "/#talk-to-us"

title-img: /assets/img/logo.png

site-css: "/assets/css/infraws.css"

keywords: "devops, sre, terraform, amazon web services, azure, cloud computing, aws, experts, outsourcing, near-sourcing"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  twitter: infraws

url-pretty: "infra.ws"

footer-img: "/assets/img/footer-bg.png"

google_analytics: "275075400"

timezone: "Europe/Athens"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "infra.ws | The DevOps powerhouse"
      share-img: "/assets/img/logo-square.jpg"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap