remote_theme: daattali/beautiful-jekyll

title: infraWS

author: infraWS PC

navbar-links:
  Services: "/#services"
  About Us: "/#aboutus"
  Clients: "/#clients"
  Open-Source: "/#portfolio"
  Contact Us: "/contact"

title-img: /assets/img/logo.png

site-css: "/assets/css/infraws.css"

keywords: "devops, DevOps, terraform, amazon web services, azure, cloud computing, aws, consultunt, developers, operations"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "info@infra.ws"
  github: infraws
  twitter: infraws

url-pretty: "infra.ws"

footer-img: "/assets/img/footer-bg.png"

google_analytics: ""

timezone: "Europe/Athens"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "DevOps house"
      share-img: "/assets/img/logo-square.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
